# Generated by Django 5.1.4 on 2025-01-05 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_frequency', models.IntegerField(choices=[(1, 'Every hour'), (6, 'Every 6 hours'), (24, 'Daily')], default=24)),
                ('email_notifications', models.BooleanField(default=True)),
                ('distance_unit', models.CharField(choices=[('km', 'Kilometers'), ('mi', 'Miles')], default='km', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
