# Generated by Django 5.1.4 on 2025-03-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='email_notifications',
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='distance_unit',
            field=models.CharField(choices=[('km', 'Kilometers'), ('mi', 'Miles')], default='mi', max_length=2),
        ),
    ]
