services:
  - type: web
    name: personal-health-manager
    env: python
    region: oregon
    buildCommand: ./build.sh
    startCommand: gunicorn health_manager.wsgi:application
    plan: free
    healthCheckPath: /login/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: personal-health-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.13.1
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: health_manager.settings
      - key: RENDER
        value: "True"
      - key: DEBUG
        value: "False"
    autoDeploy: true

  - type: redis
    name: personal-health-redis
    ipAllowList: []
    plan: free
    region: oregon

databases:
  - name: personal-health-db
    databaseName: personal_health
    user: personal_health_user
    plan: basic-256
    region: oregon 