# Generated by Django 5.1.4 on 2025-03-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegration',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
